### PR TITLE
Update x1_mini_v34.py

### PR DESCRIPTION
**Pull request by jaykijay**
My V34 has a Data Length of 100 when using v3.003.02 Firmware

### CODE REVIEW

**Comment by squishykid** [comment]
Could you please add a test including a response from your inverter under the functional tests? Then we can make sure this keeps working

**Review by squishykid — CHANGES_REQUESTED** [review]
Could you please add a test including a response from your inverter under the functional tests? Then we can make sure this keeps working

**Comment by jefft4** [comment]
@squishykid - I need this fix applied and pushed through to the HA integration as my X1miniV34 has the same firmware as @jaykijay's.  Can I do anything to help to move the PR along?

**Comment by kdehairy** [comment]
I guess it's pending adding a test. As requested earlier here.

**Comment by jefft4** [comment]
> I guess it's pending adding a test. As requested earlier here.

I read that, but I'm not sure what that involves... if someone can tell me how to add a test, I have the same inverter so I can do that.

**Comment by jefft4** [comment]
> Could you please add a test including a response from your inverter under the functional tests? Then we can make sure this keeps working

@squishykid - looking at the files, tests/response.py and tests/expected_values.py for X1_MINI_V34 already match my inverter's results; there are 100 data points in the response definition and the expected values are all present and reasonable.

**Comment by Darsstar** [comment]
Can be closed, duplicates #139

**Pull request closed without merging**
