### PR TITLE
Optional model parameter

### PR DESCRIPTION
**Pull request by rowinho**
Adding optional "model" parameter for discovery, in order to allow consumers (e.g. Homeassistant) to specify inverter model for quicker discovery.

This addresses issues where discovery takes long time to complete, sometimes not completing at all.

### CODE REVIEW

**Review by luismsousa — APPROVED** [review]

**Comment by luismsousa** [comment]
Giving it a bump to check if someone can review and merge.

**Comment by squishykid** [comment]
Can you please have a look at why the tests aren't running?

**Comment by luismsousa** [comment]
> Can you please have a look at why the tests aren't running? I would like to run the tests before doing a review

@squishykid I've re-submitted @rowinho 's PR as I couldn't push to his fork. I've opened #140  to force the trigger for the github action. https://github.com/squishykid/solax/actions/runs/7833149301 it's waiting your action for it to start. Cheers 👋

**Comment by squishykid** [comment]
I just modified the settings on `solax`, so I shouldn't need to approve the github actions as often for new contributors.

**Comment by Darsstar** [comment]
This PR can probably be closed since #145 has been merged.

**Pull request closed without merging**
