### PR TITLE
X3 Hybrid G4: Attributes added 

### PR DESCRIPTION
**Pull request by SebStaeubert**
Content:
- Unit corrections (EPS Volt.,Cur.)
- Battery Items added
- Load/Generator Power added
- Totals added (Bat. Disch./Charge, PV, EPS, Feed-in, Consumed E., etc.)

Open:
- Tests

refs #80

### CODE REVIEW

**Comment by squishykid** [comment]
Can you please pull in master? Then we can run the tests

**Comment by SebStaeubert** [comment]
> Can you please pull in master? Then we can run the tests

I  tried to. Is ok now? It is still squishykid:master. I cannot choose any other.

**Comment by squishykid** [comment]
You have the PR all correct :)

To clarify, I mean that you need to update your branch by 'pulling in' all the changes from upstream's master (squishykid/solax repo [this repo]). These changes include new testing infrastructure.

There's a guide here: https://www.atlassian.com/git/tutorials/git-forks-and-upstreams. You will need to set this repo (squishykid/solax) as the 'upstream'.

**Comment by squishykid** [comment]
There's also another set of instructions here: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork#syncing-a-fork-branch-from-the-command-line

Under the section "[Syncing a fork branch from the command line](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork#syncing-a-fork-branch-from-the-command-line)"

**Comment by SebStaeubert** [comment]
@squishykid finally, all test are fine.
I learned a lot (i have no skills in python...) :-)

**Comment by squishykid** [comment]
Nice work. Now you can raise a PR against home-assistant to bump the solax package to v3.0.5. Then your changes will be included in the next release!

**Pull request merged**
