### PR TITLE
fix(x1_boost): totals are consecutive u16 ints

### PR DESCRIPTION
**Pull request by kalosisz**
Total values are two consecutive unsigned 16bit integers for X1 Boost inverter.

### CODE REVIEW

**Review by squishykid — CHANGES_REQUESTED** [review]
Looks great. One change with your tests though: could you please add another set of expected values, rather than modifying the existing set of expected values?

The existing set of expected values is output from a known inverter, and we want that to continue working. So your new values and the existing values should coesist

**Comment by kalosisz** [comment]
I've added the new text case for the overflown case.

**Review by squishykid — CHANGES_REQUESTED** [review]
Looking right on track! You just need to reference your new test values in ‘fixtures.py’, so the tests run with your new values in addition to all of the existing values.

**Comment by kalosisz** [comment]
I should've checked! Fixture added.

**Comment by squishykid** [comment]
Nice work!

**Comment by kalosisz** [comment]
Thanks! How do new versions get released? I'd need this fix for updating the deps in [here](https://github.com/home-assistant/core/blob/dev/homeassistant/components/solax/manifest.json).

**Comment by dooblem** [comment]
Hello thanks guys. Just tested with the very last git version today.

I don't know if this is the right place to post.
My X1 Boost G3 is detected as "X1MiniV34". Is it OK ?
When removing X1MiniV34 from discovery.py, still not detected as X1 Boost.

I'm still getting some data though. From first look the data seems OK.

**Comment by Elliottmonaghan** [comment]
> Hello thanks guys. Just tested with the very last git version today.
> 
> 
> 
> I don't know if this is the right place to post.
> 
> My X1 Boost G3 is detected as "X1MiniV34". Is it OK ?
> 
> When removing X1MiniV34 from discovery.py, still not detected as X1 Boost.
> 
> 
> 
> I'm still getting some data though. From first look the data seems OK.

This is what I have experienced also. The values mostly line up but the exported power/power now values are not lined up so will not work, also the x1 boost Gen 3 uses a pack_u16 to combine a few values so some of the total values will be off. I have changed this manually on the x1 mini v34 file and got it reporting correct values but haven't delved into it on how to get it to register as an x1 boost on initial discovery.

**Pull request merged**
