### PR TITLE
Add "Inverter Temperature" for X1-Boost-Air-Mini with Wifi Pocket v2.034.06

### PR DESCRIPTION
**Pull request by arnemauer**
Add "Inverter Temperature" for X1-Boost-Air-Mini with Wifi Pocket v2.034.06 
#60

### CODE REVIEW

**Comment by arnemauer** [comment]
@squishykid here is a new pull request :) #60

**Comment by arnemauer** [comment]
@squishykid Is it possible to start the workflow and run de tests by myself instead of waiting for your approval? :)

**Comment by squishykid** [comment]
It’s a GitHub feature they implemented against crypto miners. After your first PR you won’t have to ask again. It’s not something I control, sorry.

**Comment by arnemauer** [comment]
Aah okay! So now it's okay to merge the pull request?

**Pull request merged**
