### PR TITLE
Sensor names: Remove trailing whitespace

### PR DESCRIPTION
**Pull request by mrichtarsky**

### CODE REVIEW

**Comment by mrichtarsky** [comment]
@squishykid The failures look unrelated, could you kindly take a look? Thank you!

**Comment by squishykid** [comment]
@mrichtarsky I think this should have been solved by 'include hidden files' change here: https://github.com/squishykid/solax/pull/178/files#diff-95557d53bf91069e59d82b9d8fcfaf52ec84a762858983edd5ef3c9b3e4c8191R49

can you please refresh your branch and try again?

**Comment by mrichtarsky** [comment]
@squishykid It's not solved, diff is still the same after refresh

**Comment by squishykid** [comment]
The diff will look the same, but that's just because the hidden file change is now in both branches

**Pull request merged**
