### PR TITLE
Add support for X1-Smart

### PR DESCRIPTION
**Pull request by JMacalinao**
Hi! First time contributing to this project; let me know if there's other stuff I need to add.

Added support for the X1-Smart inverter, tested using my own system so I can integrate it into Home Assistant.

Also added a make_request method for the inverter with the X-Forwarded-For workaround from #47 so I can access the API directly via LAN. (I had to downgrade the Pocket WiFi firmware to v2.033.20 as mentioned there to get it to work.)

### CODE REVIEW

**Comment by dvisser** [comment]
Epic work mate! Glad our workaround for direct access worked also! It has been flawless for us.

**Comment by squishykid** [comment]
Hey mate, thanks for taking the time to open a PR. I’ll do my best to have this reviewed and merged soon

**Comment by squishykid** [comment]
I might just have a small re-factor after we add this, but I can merge as-is and then do the fix after.

**Comment by squishykid** [comment]
@JMacalinao let me know what you think. I did add some unrelated changes though to make the linter happier

**Comment by JMacalinao** [comment]
LGTM 🙂

**Pull request merged**
