### PR TITLE
Corrected feed-in and consumed energy source and type for x3-hybrid-g4

### PR DESCRIPTION
**Pull request by darmach**
H3-Hybrid-G4: both feed-in and consumed energy values for `Total` and `DailyTotal` were swapped. Both of the above were marked as `Total`. Daily reset feed-in and consumed energy lack the `today` postfix used but other sensors.

 - Switched daily and total with each other
 - Marked reset daily as `DailyTotal`
 - Added `today` postfix to daily reset feed-in and consumed energy to adhere to the convention.
 - Corrected tests values - daily will usually be lower than total aggregate.
 
Fixes: https://github.com/home-assistant/core/issues/130742

### CODE REVIEW

**Comment by darmach** [comment]
Hi @squishykid  , I finally found a while and had a weekend off so I attempted to fix switched values for some sensors. Would you find a moment to take a look at this PR? It should fix this issue in HA: https://github.com/home-assistant/core/issues/130742

**Comment by squishykid** [comment]
Looks good to me mate! Luckily I also have a weekend off for the first time in a long time 😅

**Comment by darmach** [comment]
@squishykid What a fun update of HA I just had :D 

The sensors under my Solax device didn't seem to change, but on the bright side my energy dashboard went completely dead:
Screenshot 2024-12-04 212352

I'm afraid that this could've been a breaking change - if someone configured these entities as energy dashboard sources of data...
Will have to troubleshoot after the restore - would you have any suggestions how can I ingest the above change properly?
Maybe delete the who device and readd after upgrade or something alike?

**Comment by darmach** [comment]
Opened https://github.com/squishykid/solax/pull/179 to mitigate the issue.

**Pull request merged**
