### PR TITLE
Add support for X3-Hybiyd-G3 (tested with Solax X3 Hybrid G2)

### PR DESCRIPTION
**Pull request by ppetru**

### CODE REVIEW

**Comment by squishykid** [comment]
I wonder why my actions are not running on this :/

**Comment by squishykid** [comment]
Thank you for the contribution! It is very much appreciated!

**Comment by squishykid** [comment]
@ppetru if you want to use this change in home assistant, you will need to raise a PR there too, like these: https://github.com/home-assistant/core/pull/43564, https://github.com/home-assistant/core/pull/40330

**Comment by averter** [comment]
Thank you for this contribution. I am experiencing a discovery error (could not connect to inverter endpoint) on a solax X3-Hybrid-G3 ver 2.31.3, although curl on 5.8.8.8 works fine. I have noted that your data vol.Length is 102 and 103 or 107 and 107 but in the curl I obtained there are 69 data fields. I have then tried to add 69 to the data schema but it also did not work... Any suggestions @squishykid @ppetru ? 
For reference, I am connecting via a raspberry pi which is connected to the inverter AP via wifi. The curl is as follows (with SNs changed)
````
{"type":"X3-Hybiyd-G3","SN":"thisistheSN","ver":"2.31.3","Data":[0.2,1.0,563.6,292.4,0.9,229.8,358,42,3.5,15234.7,-21,163,310,346.30,0.00,-4,29.0,5.2,0.0,0.0,0.00,31.00,0,0,0,0.0,0.0,0.00,0.00,0,0,0,0.0,0.0,0.00,0.00,0,0,0,0.0,0.0,4714.03,13977.85,125,187,46,1.0,0.7,231.2,229.1,49.99,49.99,49.99,0.0,0.0,0,0.00,0,0,0,0,0,0,0,0,0,0,0,2],"Information":[10.000,5,"X3-Hybiyd-G3","thisisanothernumber",1,3.31,0.00,3.27,1.05]}
````

**Comment by ppetru** [comment]
Mine no longer works either after upgrading to ver 2.034.06. I've been trying to reverse engineer the new data format but lack of time is making it very slow..

Either way: my data length is 200 now so whatever 2.31.3 is doing is unlikely to be solved if and when I get mine to work again, sorry.

**Comment by squishykid** [comment]
@averter would you be able to give us a breakdown of each field in the `"Data"` list please? Then we can make the changes to better support your inverter with this library. There's some info on this here https://github.com/squishykid/solax/wiki/Adding-Support-for-Your-Inverter

**Comment by squishykid** [comment]
@averter please also consider making a new issue for this, then it is easier to track the changes.

**Pull request merged**
